version: "3.7"

services:
  db:
    image: postgres
    container_name: database_studiests
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: studiests
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
